<!DOCTYPE html>
    <html lang="en">
        <head>
            <title>PET NURSERY</title>
            <meta charset="UTF-8">
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
        </head>

        <body>
            <div class="header">
                <h1>ПИТОМНИК ДЛЯ ЖИВОТНЫХ</h1>
            </div>

            <div class="navbar">
                <a href="/">Главная</a>
                <a href="#">Добавить</a>
                <a href="#">Список всех</a>
                <a href="#">Изменить данные</a>
            </div>

            <div class="row">
                <div class="main">Some text</div>
            </div>
        </body>
    </html>