<!DOCTYPE html>
<html lang="en">
    <head>
        <title>PET NURSERY</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
        <script src="/static/js/jscripts.js"></script>
    </head>
    <body>
        <div class="header">
            <h1>ПИТОМНИК ДЛЯ ЖИВОТНЫХ</h1>
            <p>Добро пожаловать!</p>
        </div>

        <div class="navbar">
            <a href="/">Главная</a>
            <a href="/home_pets">Домашние питомцы</a>
            <a href="/pack_pets">Вьючные животные</a>
        </div>


    </body>
</html>