<!DOCTYPE html>
<html lang="en">
    <head>
        <title>PET NURSERY</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="/static/css/styles.css">
    </head>
    <body>
        <div class="header">
            <h1>ВЬЮЧНЫЕ ЖИВОТНЫЕ</h1>
        </div>
        <div class="navbar">
            <a href="/">Главная страница</a>
            <a href="/home_pets">Домашние животные</a>
            <a href="/pack_pets">Вьючные животные</a>
            <a href="#" class="right">Выборка</a>
        </div>
    </body>
</html>